# Generated by Django 4.2.4 on 2023-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.TextField(verbose_name='Domain name')),
                ('ping_of_domain', models.TextField(verbose_name='Ping')),
            ],
        ),
    ]
